// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fttyhcpjzqqkppgbqdhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dHloY3BqenFxa3BwZ2JxZGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyODgwNDksImV4cCI6MjA3Mjg2NDA0OX0.HO1GN_lDfHq5G_KjXtuQJ4U2pi6ljlA1auwEkMKD2fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});